# Zola configuration
# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://bradschwartz.io"
title = "/home/bradschwartz"
description = "There's no place like $HOME"
author = "Brad Schwartz"

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

# Everything in this section lives in `extra` in Tera
[extra]
email = "baschwartz95@gmail.com"
github_username = "bradschwartz"
linkedin_username = "baschwa"

# lowercase_links = true

# https://www.getzola.org/documentation/content/syntax-highlighting/
[markdown.highlighting]
# available themes: https://textmate-grammars-themes.netlify.app/
light_theme = "github-light-high-contrast"
dark_theme = "github-dark-high-contrast"
